### PR TITLE
Fix type to enable compilation

### PR DESCRIPTION
**Pull request by pstef**
Before this commit I got a compilation error about type mismatch between short int * and unsigned char *.

To keep the buffer size intact, I double the number of elements since char is usually half the size of short int.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Sorry it took so long to merge this.

**Comment by cmitu** [comment]
The changes have triggered a sound volume regression in the core, reported in #96 and also in the RetroPie forums. 

The modifications here should be reverted and https://github.com/libretro/libretro-atari800/pull/95 should be applied instead, since it resolves the same issue and has no regression as far as audio volume is concerned.

**Comment by pstef** [comment]
> The changes have triggered a sound volume regression in the core, reported in #96 and also in the RetroPie forums.

How do we know it's this commit exactly that caused the regression? The report doesn't provide any details.

> The modifications here should be reverted and #95 should be applied instead, since it resolves the same issue and has no regression as far as audio volume is concerned.

It's possible, but I would like to understand how that happened and what's the difference between the two proposed alternative changes that make the difference in practice before we choose one over the other.

**Comment by cmitu** [comment]
> How do we know it's this commit exactly that caused the regression? The report doesn't provide any details.
> 

The report in the issue does not, but I've compiled the core with/without the changes in the PR after receiving the report in the forums. I'm assuming it has the same cause, given the seldom changes in the core repository and the timing of the report.
